.ALIASES
R_RS            RS(1=N00139 2=N00156 ) CN @EX1.SCHEMATIC1(sch_1):INS26@ANALOG.R.Normal(chips)
R_RL            RL(1=0 2=N00156 ) CN @EX1.SCHEMATIC1(sch_1):INS42@ANALOG.R.Normal(chips)
L_L1            L1(1=N00156 2=0 ) CN @EX1.SCHEMATIC1(sch_1):INS67@ANALOG.L.Normal(chips)
C_C1            C1(1=0 2=N00156 ) CN @EX1.SCHEMATIC1(sch_1):INS92@ANALOG.C.Normal(chips)
V_V1            V1(+=N00139 -=0 ) CN @EX1.SCHEMATIC1(sch_1):INS119@SOURCE.VAC.Normal(chips)
.ENDALIASES
